version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'taxi_db') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'taxi_homework') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_trip
      - name: yellow_trip